# Generated by Django 4.1.4 on 2022-12-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='static/assets/img/default.png', null=True, upload_to='noticia'),
        ),
    ]
