# Generated by Django 4.1.4 on 2022-12-23 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_alter_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticia.noticia')),
            ],
        ),
    ]
